#!/usr/bin/env node

import { writeFile } from "fs/promises";
import { join } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";
import { config } from "dotenv";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = join(__dirname, "..");

config({ path: join(ROOT_DIR, ".env.local") });

const API_KEY = process.env.YOUTUBE_API_KEY;
const CHANNEL_ID = process.env.YOUTUBE_CHANNEL_ID;
const API_BASE = "https://www.googleapis.com/youtube/v3";

if (!API_KEY || !CHANNEL_ID) {
  console.error(
    "❌ Missing YOUTUBE_API_KEY or YOUTUBE_CHANNEL_ID in .env.local"
  );
  process.exit(1);
}

/**
 * Slugify a string for URL-safe usage.
 */
function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 80);
}

/**
 * Convert ISO 8601 duration (PT4M13S) to human-readable (4:13).
 */
function formatDuration(isoDuration) {
  const match = isoDuration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return "0:00";

  const hours = parseInt(match[1] || "0", 10);
  const minutes = parseInt(match[2] || "0", 10);
  const seconds = parseInt(match[3] || "0", 10);

  const paddedSeconds = seconds.toString().padStart(2, "0");

  if (hours > 0) {
    const paddedMinutes = minutes.toString().padStart(2, "0");
    return `${hours}:${paddedMinutes}:${paddedSeconds}`;
  }

  return `${minutes}:${paddedSeconds}`;
}

/**
 * Fetch JSON from the YouTube Data API v3.
 */
async function ytFetch(endpoint, params) {
  const url = new URL(`${API_BASE}/${endpoint}`);
  url.searchParams.set("key", API_KEY);
  for (const [k, v] of Object.entries(params)) {
    url.searchParams.set(k, v);
  }

  const res = await fetch(url.toString());
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`YouTube API error ${res.status}: ${body}`);
  }
  return res.json();
}

/**
 * Get the "uploads" playlist ID for a channel.
 */
async function getUploadsPlaylistId() {
  const data = await ytFetch("channels", {
    part: "contentDetails",
    id: CHANNEL_ID,
  });

  if (!data.items || data.items.length === 0) {
    throw new Error(`Channel ${CHANNEL_ID} not found`);
  }

  return data.items[0].contentDetails.relatedPlaylists.uploads;
}

/**
 * Fetch all video IDs from the uploads playlist (handles pagination).
 */
async function getAllVideoIds(playlistId) {
  const ids = [];
  let pageToken = "";

  do {
    const params = {
      part: "snippet",
      playlistId,
      maxResults: "50",
    };
    if (pageToken) params.pageToken = pageToken;

    const data = await ytFetch("playlistItems", params);

    for (const item of data.items) {
      ids.push(item.snippet.resourceId.videoId);
    }

    pageToken = data.nextPageToken || "";
  } while (pageToken);

  return ids;
}

/**
 * Fetch full details for a batch of video IDs (max 50 per call).
 */
async function getVideoDetails(videoIds) {
  const videos = [];

  for (let i = 0; i < videoIds.length; i += 50) {
    const batch = videoIds.slice(i, i + 50);
    const data = await ytFetch("videos", {
      part: "snippet,statistics,contentDetails",
      id: batch.join(","),
    });

    for (const item of data.items) {
      const thumbnail =
        item.snippet.thumbnails.maxres?.url ||
        item.snippet.thumbnails.high?.url ||
        item.snippet.thumbnails.medium?.url ||
        item.snippet.thumbnails.default?.url ||
        "";

      const usedSlugs = new Set(videos.map((v) => v.slug));
      let slug = `${slugify(item.snippet.title)}-${item.id}`;
      if (usedSlugs.has(slug)) {
        slug = `${slug}-${Date.now()}`;
      }

      videos.push({
        id: item.id,
        slug,
        title: item.snippet.title,
        description: item.snippet.description || "",
        publishedAt: item.snippet.publishedAt,
        thumbnailUrl: thumbnail,
        duration: item.contentDetails.duration,
        durationFormatted: formatDuration(item.contentDetails.duration),
        viewCount: parseInt(item.statistics.viewCount || "0", 10),
        likeCount: parseInt(item.statistics.likeCount || "0", 10),
        tags: item.snippet.tags || [],
        channelTitle: item.snippet.channelTitle,
      });
    }
  }

  return videos;
}

/**
 * Generate the TypeScript source file content.
 */
function generateTsFile(videos) {
  const lines = [
    "/**",
    " * Auto-generated by scripts/update-youtube.mjs",
    " * Do not edit manually — run: pnpm update-youtube",
    " */",
    "",
    "export interface YouTubeVideo {",
    "  id: string;",
    "  slug: string;",
    "  title: string;",
    "  description: string;",
    "  publishedAt: string;",
    "  thumbnailUrl: string;",
    "  duration: string;",
    "  durationFormatted: string;",
    "  viewCount: number;",
    "  likeCount: number;",
    "  tags: string[];",
    "  channelTitle: string;",
    "}",
    "",
    `export const youtubeVideos: YouTubeVideo[] = ${JSON.stringify(videos, null, 2)};`,
    "",
  ];

  return lines.join("\n");
}

async function main() {
  try {
    console.log("🎬 Fetching YouTube channel videos...\n");

    console.log("📺 Getting uploads playlist...");
    const uploadsId = await getUploadsPlaylistId();
    console.log(`   ✓ Playlist: ${uploadsId}`);

    console.log("📋 Fetching video IDs...");
    const videoIds = await getAllVideoIds(uploadsId);
    console.log(`   ✓ Found ${videoIds.length} videos`);

    if (videoIds.length === 0) {
      console.log("⚠️  No videos found on this channel.");
      const emptyContent = generateTsFile([]);
      const outPath = join(ROOT_DIR, "src/data/youtube.ts");
      await writeFile(outPath, emptyContent, "utf-8");
      console.log("✅ Wrote empty src/data/youtube.ts");
      return;
    }

    console.log("🔍 Fetching video details...");
    const videos = await getVideoDetails(videoIds);

    videos.sort(
      (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
    );

    console.log(`   ✓ Fetched details for ${videos.length} videos`);

    const outPath = join(ROOT_DIR, "src/data/youtube.ts");
    await writeFile(outPath, generateTsFile(videos), "utf-8");
    console.log(`\n✅ Wrote src/data/youtube.ts with ${videos.length} videos`);

    console.log("\n📈 Summary:");
    console.log("━".repeat(50));
    console.log(`Total Videos: ${videos.length}`);
    console.log(
      `Total Views:  ${videos.reduce((s, v) => s + v.viewCount, 0).toLocaleString()}`
    );
    console.log(
      `Latest:       ${videos[0]?.title || "N/A"}`
    );
    console.log("━".repeat(50));
  } catch (error) {
    console.error("\n❌ Error:", error.message);
    process.exit(1);
  }
}

main();
