/**
 * Auto-generated by scripts/update-youtube.mjs
 * Do not edit manually — run: pnpm update-youtube
 */

export interface YouTubeVideo {
  id: string;
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  thumbnailUrl: string;
  duration: string;
  durationFormatted: string;
  viewCount: number;
  likeCount: number;
  tags: string[];
  channelTitle: string;
}

export const youtubeVideos: YouTubeVideo[] = [
  {
    id: "8OnHTRBT85k",
    slug: "layr-founders-video-yc-fall-2026-application-8OnHTRBT85k",
    title: "Layr Founders Video | YC Fall 2026 Application",
    description:
      "Layr founders video submitted with our YC Fall 2026 application.\n\nWe are Chahat, Harshvardhan, Rishi, and Vansh — four engineering undergrads from NIT Jalandhar. All four of us write code.\n\nLayr is the decision layer between customer evidence and execution. AI made writing code faster. Choosing the right thing to build is now the bottleneck.\n\nWe connect the tools product teams already use, turn scattered signals into reviewed product memory, and help teams decide what to build next — with the evidence linked behind every call.\n\nThis is our one-minute founders video for YC Fall 2026. Our earlier Summer 2026 founders video is here: [link Video 1]\n\nProduct: https://uselayr.com\nDemo: https://youtu.be/tT1EGKq0d28?si=X3HFJIC9PUmSrkN_\n\n#Layr #YCombinator #YC #Founders #Startup #AI #ProductManagement #F26",
    publishedAt: "2026-08-01T09:38:52Z",
    thumbnailUrl: "https://i.ytimg.com/vi/8OnHTRBT85k/maxresdefault.jpg",
    duration: "PT47S",
    durationFormatted: "0:47",
    viewCount: 20,
    likeCount: 2,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "VHDx_8i3it8",
    slug: "layr-founders-video-yc-summer-2026-application-VHDx_8i3it8",
    title: "Layr Founders Video | YC Summer 2026 Application",
    description:
      "Layr founders video submitted with our YC Summer 2026 application.\n\nWe are Chahat, Harshvardhan, Rishi, and Vansh — four engineering undergrads from NIT Jalandhar building Layr.\n\nLayr helps product teams know what to build next, backed by real customer evidence. Product context is scattered across Slack, Jira, calls, tickets, and docs. Layr connects those sources and turns them into evidence-backed priorities and specs.\n\nThis is our one-minute founders video for YC — just the team talking, no product demo.\n\nProduct: https://uselayr.com\nDemo: https://youtu.be/tT1EGKq0d28?si=X3HFJIC9PUmSrkN_\n\n#Layr #YCombinator #YC #Founders #Startup #ProductManagement #S26",
    publishedAt: "2026-08-01T09:38:47Z",
    thumbnailUrl: "https://i.ytimg.com/vi/VHDx_8i3it8/maxresdefault.jpg",
    duration: "PT56S",
    durationFormatted: "0:56",
    viewCount: 11,
    likeCount: 1,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "tT1EGKq0d28",
    slug: "layr-product-demo-from-slack-jira-calls-to-evidence-backed-specs-tT1EGKq0d28",
    title:
      "Layr Product Demo | From Slack, Jira & Calls to Evidence-Backed Specs",
    description:
      "Know what to build next — from evidence, not noise.\n\nLayr is the AI product decision layer for product teams. It connects Slack, Jira, Linear, customer calls, support tickets, and docs, then turns scattered signals into clear priorities, specs, and task drafts - with the customer evidence linked behind every recommendation.\n\nIn this demo, you’ll see how Layr helps you: • Cut context-hunting across tools\n• Prioritize from real customer language, not the loudest opinion\n• Move from signal → recommendation → draft spec without losing the “why”\n\nRead-only by default. Sources linked in every answer. Human approval before anything is written back.\n\nJoin the waitlist: https://uselayr.com\n\n#Layr #ProductManagement #AIProduct #Roadmap #PRD #CustomerFeedback #SaaS #Demo",
    publishedAt: "2026-07-24T04:37:53Z",
    thumbnailUrl: "https://i.ytimg.com/vi/tT1EGKq0d28/maxresdefault.jpg",
    duration: "PT3M",
    durationFormatted: "3:00",
    viewCount: 10,
    likeCount: 1,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "ubd_wQAHtjw",
    slug: "simplify-your-bookmark-management-with-webmark-ubd_wQAHtjw",
    title: "Simplify Your Bookmark Management - with Webmark",
    description:
      "Webmark\nA modern bookmark manager with categories, drag-and-drop organization, browser import, a one-click bookmarklet, AI-powered sorting, and multi-device sessions.\n\nLive: webmark.chahatkesh.me\n\nFeatures\n• Google sign-in: OAuth with httpOnly cookies, refresh rotation, and rate-limited auth\n• Device limit: Up to 2 active sessions (any device type); revoke from Profile or during sign-in\n• Categories: Custom names, emoji icons, and color themes\n• Bookmarks: Add, edit, notes, delete, and reorder (within and across categories)\n• Search: Instant client-side filtering across names, URLs, notes, and categories\n• Bookmarklet: Save any page from the toolbar; AI can assign a category\n• Import: Chrome/Firefox HTML exports with monthly quotas\n• AI sort: Bulk reorganize with OpenAI (credit-gated; revert supported)\n• Onboarding: Username setup with seeded starter categories\n• Profile: Display name, credits, click analytics, top bookmarks, devices\n\nBuilt by https://chahatkesh.me",
    publishedAt: "2026-07-15T10:32:50Z",
    thumbnailUrl: "https://i.ytimg.com/vi/ubd_wQAHtjw/maxresdefault.jpg",
    duration: "PT1M11S",
    durationFormatted: "1:11",
    viewCount: 14,
    likeCount: 1,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "7b81tJgCdBM",
    slug: "minor-project-intelligent-pesticide-sprinkling-system-7b81tJgCdBM",
    title: "Minor Project: Intelligent Pesticide Sprinkling System",
    description:
      "An IoT and AI system that detects tomato-leaf infection severity and sprays pesticide proportionally, reducing waste while logging every event to a live dashboard.",
    publishedAt: "2026-06-04T11:06:42Z",
    thumbnailUrl: "https://i.ytimg.com/vi/7b81tJgCdBM/maxresdefault.jpg",
    duration: "PT1M16S",
    durationFormatted: "1:16",
    viewCount: 50,
    likeCount: 2,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "Y7yZ_eYQ5Lo",
    slug: "building-openlearn-behind-the-scenes-of-development-part-1-Y7yZ_eYQ5Lo",
    title: "Building OpenLearn: Behind the Scenes of Development | Part-1",
    description: "",
    publishedAt: "2026-02-02T08:00:21Z",
    thumbnailUrl: "https://i.ytimg.com/vi/Y7yZ_eYQ5Lo/maxresdefault.jpg",
    duration: "PT1M18S",
    durationFormatted: "1:18",
    viewCount: 17,
    likeCount: 1,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "rA6qcsEjAWc",
    slug: "kisaanmithraa-empowering-farmers-with-ai-community-smart-markets-gsc-2025-demo-rA6qcsEjAWc",
    title:
      "KisaanMithraa | Empowering Farmers with AI, Community & Smart Markets | GSC 2025 Demo",
    description:
      "KisaanMithraa is an AI-powered mobile app designed to revolutionize farming for rural communities.\n\n🚜 From market access and real-time price forecasts to multilingual chatbot support and cooperative pooling — KisaanMithraa is a one-stop digital solution for farmers.\n\n👨‍🌾 Built using Flutter, Google Cloud, Gemini, Dialogflow, and Firebase, this project is part of the Google Solution Challenge 2025, aiming to bridge technology and agriculture at the grassroots level.\n\n🌱 Key Features:\n\nSmart Market Access with Price Forecasting\n\nMithraaBot: Multilingual AI Assistant\n\nCooperative Pooling & Community Sharing\n\nEmergency SOS Support\n\nRegional Language Knowledge Hub\n\n🔗 Explore More:\nGitHub Repository : \nLive on Google IDX : \n\n💬 Like, share, and join us in empowering India’s farmers—one field at a time.",
    publishedAt: "2026-01-17T10:18:51Z",
    thumbnailUrl: "https://i.ytimg.com/vi/rA6qcsEjAWc/maxresdefault.jpg",
    duration: "PT2M34S",
    durationFormatted: "2:34",
    viewCount: 55,
    likeCount: 4,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "lyXBpUsi7Us",
    slug: "openlearns-first-twitter-space-cohort-learning-leagues-community-at-nit-jalandha-lyXBpUsi7Us",
    title:
      "OpenLearn's First Twitter Space | Cohort Learning, Leagues & Community at NIT Jalandhar",
    description:
      "🎙️ OpenLearn's First Twitter Space — full recording\n\nIn our debut X (Twitter) Space, the OpenLearn team opens up about who we are, what we're building, and how students at NIT Jalandhar can learn, compete, and grow together.\n\nOpenLearn is a peer-driven learning platform where students explore new fields, build real projects, and grow alongside passionate peers — through structured Leagues, cohort-based progression, badges, leaderboards, and the Accelerate program.\n\n🔹 What we cover in this Space:\n• What OpenLearn is and why we started it\n• How cohorts work (Summer n.0 & Fall n.5)\n• Skill-based Leagues — ML, Finance, Quantum Computing, Soft Skills & more\n• The Pioneer → Pathfinder journey and community roles\n• Cohort 1.5 — how to join and what to expect\n• Accelerate program, capstone projects & upcoming events\n• Q&A with the community\n\n━━━━━━━━━━━━━━━━━━━━\n🔗 Links\nWebsite: https://openlearn.chahatkesh.me\nJoin Cohort 1.5: https://openlearn.org.in/cohorts\nFollow on X: https://x.com/OpenLearn_nitj\nInstagram: https://www.instagram.com/openlearn.org.in\n\n━━━━━━━━━━━━━━━━━━━━\n🏆 OpenLearn Leagues\n• Machine Learning\n• Finance\n• Quantum Computing\n• Soft Skills\n• Competitive Programming\n• IoT & more\n\nLearn in structured weeks, complete resources, earn badges, and climb the leaderboard — all alongside your peers at NIT Jalandhar.\n\n━━━━━━━━━━━━━━━━━━━━\n#OpenLearn #NITJ #NITJalandhar #Learning #CohortLearning #MachineLearning #Finance #QuantumComputing #StudentCommunity #EdTech #TwitterSpace #XSpace\n\n━━━━━━━━━━━━━━━━━━━━\nAbout OpenLearn\n\nOpenLearn is structured, peer-driven, focused, and truly open — no barriers, no costs, just learning and building. From Grand Orientation with 450+ attendees to hackathons, mentorship sessions, and build-alongs, we're building a community where students don't just consume content — they create, collaborate, and accelerate.\n\nSubscribe for more OpenLearn sessions, event recaps, and community updates.",
    publishedAt: "2026-01-17T10:10:25Z",
    thumbnailUrl: "https://i.ytimg.com/vi/lyXBpUsi7Us/maxresdefault.jpg",
    duration: "PT1H8M5S",
    durationFormatted: "1:08:05",
    viewCount: 17,
    likeCount: 0,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "qCr25SQ8Zg8",
    slug: "building-satark-ai-ai-powered-legal-assistant-qCr25SQ8Zg8",
    title: "Building Satark AI | AI-Powered Legal Assistant",
    description:
      "Join us as we build Satark AI 🚀⚖️\n\nSatark AI is an AI-powered legal assistant designed to help law enforcement officers, legal professionals, and citizens with legal research, document automation, crime pattern detection, and real-time legal insights.\n\n🔹 For Police Officers – Faster FIR retrieval, automated legal documentation, and crime trend analysis.\n🔹 For Lawyers – AI-powered case law research, instant legal drafting, and real-time legal updates.\n🔹 For Citizens – Easy access to legal knowledge, voice search support, and guidance on rights & laws.\n\nPowered by Multi-RAG, LLMs (OpenAI & Groq), and Pathway Framework, Satark AI brings efficiency, accuracy, and accessibility to legal workflows.\n\n🔥 Watch how we developed this project in just 24 hours at Code Kshetra 2.0!\n\n#Hackathon #SatarkAI #LegalTech #AI #GenAI #LawTech",
    publishedAt: "2025-02-22T06:44:21Z",
    thumbnailUrl: "https://i.ytimg.com/vi/qCr25SQ8Zg8/maxresdefault.jpg",
    duration: "PT9M8S",
    durationFormatted: "9:08",
    viewCount: 139,
    likeCount: 1,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "siLfjw4gTPA",
    slug: "servolend-ai-powered-los-team-rio-siLfjw4gTPA",
    title: "Servolend - AI powered LOS | Team Rio",
    description:
      "The problem Servolend solves\nProblem\nThe banking and financial sector faces significant challenges in their loan origination processes:\n\n1. Speed and Efficiency\nSlow decision-making compared to online lenders\nComplex, manual processes causing delays\nLimited ability to conduct virtual appraisals\n\n2. Technical Limitations\nIntegration difficulties with existing systems\nScalability issues with increasing loan applications\nSecurity concerns with sensitive financial data\n\n3. Regulatory Compliance\nFrequent regulatory changes requiring system updates\nNeed for robust compliance tracking\n\n4. Cost and Resources\nHigh implementation costs\nResource-intensive manual processes\nTraining requirements for new technology\n\nProposed Solution\nServoLend\nAn AI-powered lending platform that revolutionizes the loan processing experience for both financial institutions and borrowers.\n\nTraditional lending is slow, paper-heavy, and prone to bias. ServoLend streamlines the entire lending process through AI automation, reducing a 2-week approval process to just minutes while ensuring fair, data-driven decisions and reduced operational costs for lenders.\n\nChallenges we ran into\nChallenges We Ran Into\nSlow ML Predictions: Our initial model was too slow for real-time decisions. Solved by optimizing the model and adding a caching layer.\n\nAuth Complexity: Syncing auth between web and mobile apps was tricky. Built a unified JWT system that works across platforms.\n\nDocument Processing: Handling large documents securely was challenging. Implemented client-side compression and secure processing queue.\n\nReal-time Updates: Keeping users updated on loan status was complex. Added WebSocket connections for instant notifications.\n\n#thaparuniversity #hacktu #hackathon #servolend #finanace",
    publishedAt: "2025-02-09T06:44:23Z",
    thumbnailUrl: "https://i.ytimg.com/vi/siLfjw4gTPA/hqdefault.jpg",
    duration: "PT15M40S",
    durationFormatted: "15:40",
    viewCount: 62,
    likeCount: 2,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
];
