/**
 * Auto-generated by scripts/update-youtube.mjs
 * Do not edit manually — run: pnpm update-youtube
 */

export interface YouTubeVideo {
  id: string;
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  thumbnailUrl: string;
  duration: string;
  durationFormatted: string;
  viewCount: number;
  likeCount: number;
  tags: string[];
  channelTitle: string;
}

export const youtubeVideos: YouTubeVideo[] = [
  {
    id: "Y7yZ_eYQ5Lo",
    slug: "building-openlearn-behind-the-scenes-of-development-part-1-Y7yZ_eYQ5Lo",
    title: "Building OpenLearn: Behind the Scenes of Development | Part-1",
    description: "",
    publishedAt: "2026-02-02T08:00:21Z",
    thumbnailUrl: "https://i.ytimg.com/vi/Y7yZ_eYQ5Lo/maxresdefault.jpg",
    duration: "PT1M18S",
    durationFormatted: "1:18",
    viewCount: 14,
    likeCount: 1,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "rA6qcsEjAWc",
    slug: "kisaanmithraa-empowering-farmers-with-ai-community-smart-markets-gsc-2025-demo-rA6qcsEjAWc",
    title:
      "KisaanMithraa | Empowering Farmers with AI, Community & Smart Markets | GSC 2025 Demo",
    description:
      "KisaanMithraa is an AI-powered mobile app designed to revolutionize farming for rural communities.\n\n🚜 From market access and real-time price forecasts to multilingual chatbot support and cooperative pooling — KisaanMithraa is a one-stop digital solution for farmers.\n\n👨‍🌾 Built using Flutter, Google Cloud, Gemini, Dialogflow, and Firebase, this project is part of the Google Solution Challenge 2025, aiming to bridge technology and agriculture at the grassroots level.\n\n🌱 Key Features:\n\nSmart Market Access with Price Forecasting\n\nMithraaBot: Multilingual AI Assistant\n\nCooperative Pooling & Community Sharing\n\nEmergency SOS Support\n\nRegional Language Knowledge Hub\n\n🔗 Explore More:\nGitHub Repository : \nLive on Google IDX : \n\n💬 Like, share, and join us in empowering India’s farmers—one field at a time.",
    publishedAt: "2026-01-17T10:18:51Z",
    thumbnailUrl: "https://i.ytimg.com/vi/rA6qcsEjAWc/maxresdefault.jpg",
    duration: "PT2M34S",
    durationFormatted: "2:34",
    viewCount: 53,
    likeCount: 4,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "lyXBpUsi7Us",
    slug: "openlearns-first-twitter-space-lyXBpUsi7Us",
    title: "OpenLearn's First Twitter Space",
    description: "",
    publishedAt: "2026-01-17T10:10:25Z",
    thumbnailUrl: "https://i.ytimg.com/vi/lyXBpUsi7Us/maxresdefault.jpg",
    duration: "PT1H8M6S",
    durationFormatted: "1:08:06",
    viewCount: 11,
    likeCount: 0,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "qCr25SQ8Zg8",
    slug: "building-satark-ai-ai-powered-legal-assistant-qCr25SQ8Zg8",
    title: "Building Satark AI | AI-Powered Legal Assistant",
    description:
      "Join us as we build Satark AI 🚀⚖️\n\nSatark AI is an AI-powered legal assistant designed to help law enforcement officers, legal professionals, and citizens with legal research, document automation, crime pattern detection, and real-time legal insights.\n\n🔹 For Police Officers – Faster FIR retrieval, automated legal documentation, and crime trend analysis.\n🔹 For Lawyers – AI-powered case law research, instant legal drafting, and real-time legal updates.\n🔹 For Citizens – Easy access to legal knowledge, voice search support, and guidance on rights & laws.\n\nPowered by Multi-RAG, LLMs (OpenAI & Groq), and Pathway Framework, Satark AI brings efficiency, accuracy, and accessibility to legal workflows.\n\n🔥 Watch how we developed this project in just 24 hours at Code Kshetra 2.0!\n\n#Hackathon #SatarkAI #LegalTech #AI #GenAI #LawTech",
    publishedAt: "2025-02-22T06:44:21Z",
    thumbnailUrl: "https://i.ytimg.com/vi/qCr25SQ8Zg8/maxresdefault.jpg",
    duration: "PT9M8S",
    durationFormatted: "9:08",
    viewCount: 130,
    likeCount: 1,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
  {
    id: "siLfjw4gTPA",
    slug: "servolend-ai-powered-los-team-rio-siLfjw4gTPA",
    title: "Servolend - AI powered LOS | Team Rio",
    description:
      "The problem Servolend solves\nProblem\nThe banking and financial sector faces significant challenges in their loan origination processes:\n\n1. Speed and Efficiency\nSlow decision-making compared to online lenders\nComplex, manual processes causing delays\nLimited ability to conduct virtual appraisals\n\n2. Technical Limitations\nIntegration difficulties with existing systems\nScalability issues with increasing loan applications\nSecurity concerns with sensitive financial data\n\n3. Regulatory Compliance\nFrequent regulatory changes requiring system updates\nNeed for robust compliance tracking\n\n4. Cost and Resources\nHigh implementation costs\nResource-intensive manual processes\nTraining requirements for new technology\n\nProposed Solution\nServoLend\nAn AI-powered lending platform that revolutionizes the loan processing experience for both financial institutions and borrowers.\n\nTraditional lending is slow, paper-heavy, and prone to bias. ServoLend streamlines the entire lending process through AI automation, reducing a 2-week approval process to just minutes while ensuring fair, data-driven decisions and reduced operational costs for lenders.\n\nChallenges we ran into\nChallenges We Ran Into\nSlow ML Predictions: Our initial model was too slow for real-time decisions. Solved by optimizing the model and adding a caching layer.\n\nAuth Complexity: Syncing auth between web and mobile apps was tricky. Built a unified JWT system that works across platforms.\n\nDocument Processing: Handling large documents securely was challenging. Implemented client-side compression and secure processing queue.\n\nReal-time Updates: Keeping users updated on loan status was complex. Added WebSocket connections for instant notifications.\n\n#thaparuniversity #hacktu #hackathon #servolend #finanace",
    publishedAt: "2025-02-09T06:44:23Z",
    thumbnailUrl: "https://i.ytimg.com/vi/siLfjw4gTPA/hqdefault.jpg",
    duration: "PT15M40S",
    durationFormatted: "15:40",
    viewCount: 54,
    likeCount: 2,
    tags: [],
    channelTitle: "Chahat Kesharwani",
  },
];
